# AgentVmSize = "Standard_F8s_v2"
# AppVmSize = "Standard_F8s_v2"
# ResourceGroupLocation = "East US"
# UserEmailTag = "terraform@example.com"
# UserLoginTag = "terraform"
# UserProjectTag = "cloud-ist"