apiVersion: apps/v1
kind: Deployment
metadata:
    name: cyperf-agent-client-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: cyperf-agent
    template:
        metadata:
            labels:
                app: cyperf-agent
        spec:
            containers:
                -   name: cyperf-agent-client
                    image: public.ecr.aws/keysight/cyperf-agent:latest
                    env:
                    -   name: AGENT_CONTROLLER
                        value: "10.36.66.111"
                    -   name: AGENT_TAGS
                        value: "K8s-Group=CyPerf-Agent-Client,node-owner=User"
                    securityContext:
                        privileged: false
                        capabilities:
                          add: ["NET_ADMIN", "IPC_LOCK"]
                    resources:
                        limits:
                            memory: "4Gi"
                            #cpu: "3.5"
                            ## skipping requests means limits=requests
                            ## with 3.5 for 8 core node it should be able to run 2 replicas
                            ## but experiments needed to see how other pods react for perf configs.
                        requests:
                            memory: "2Gi"

            nodeSelector:
                agenttype: client
            #affinity:
            #    podAntiAffinity:
            #        requiredDuringSchedulingIgnoredDuringExecution:
            #        - labelSelector:
            #            matchExpressions:
            #            - key: app
            #              operator: In
            #              values:
            #              - cyperf-agent
            #          topologyKey: "kubernetes.io/hostname"
