# AgentInstanceType = "c5n.9xlarge"
# ApiMaxRetries = 1
# AppInstanceType = "c5.2xlarge"
# AwsAccessCredentialsAccessKey = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
# AwsAccessCredentialsSecretKey = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"
# InboundIPv4CidrBlocks = [ "1.1.1.1/32" ]
# Private1SubnetAvailabilityZone = "us-east-1a"
# Private2SubnetAvailabilityZone = "us-east-1a"
# PublicSubnetAvailabilityZone = "us-east-1a"
# Region = "us-east-1"
# UserEmailTag = "terraform@example.com"
# UserLoginTag = "terraform"
# UserProjectTag = "cloud-ist"