# AwsAccessCredentialsAccessKey = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
# AwsAccessCredentialsSecretKey = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"
# InboundIPv4CidrBlock = "1.1.1.1/32"
# UserEmailTag = "terraform@example.com"
# UserLoginTag = "terraform"