---
- name: Configures CyPerf in Commercial Off-The-Shelf (COTS) Hardware
  hosts: all

  vars_files:
    - variables.yml

  tasks:
    - name: Copying the Appsec Agent installer {{ VarAppsecInstaller }} in Node(s)
      copy:
        src: ../file_repo/{{ VarAppsecInstaller }}
        dest: /tmp/{{ VarAppsecInstaller }}
  
    - name: Installing the Appsec Agent installer in Node(s)
      become: yes
      shell: 'cd /tmp && sudo apt install ./{{ VarAppsecInstaller }}'
    
    - name: Configuring Node(s)
      become: yes
      shell: |
         'cyperfagent interface test set {{ VarTestInterface }}'
         'cyperfagent interface management set {{ VarManagementInterface }}'
         'cyperfagent controller set {{ VarController }}'

    - name: Restarting portmanager service in Node(s)
      become: yes
      shell: 'cyperfagent configuration reload'
